apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     300s # By default, scrape targets every 15 seconds.

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: 'intersight'

        static_configs:
          - targets: ['prom-intersight-metrics:2112']
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - name: main
        image: prom/prometheus
        ports: 
        - containerPort: 9090
        volumeMounts:
          - name: config
            mountPath: /etc/prometheus/
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels: 
    name: prometheus
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector: 
    name: prometheus
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Xss-Protection: 1; mode=block always;";
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: prometheus
            port: 
              number: 9090
        path: /prometheus(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: prometheus
            port: 
              number: 9090
        path: /graph(/|$)(.*)
        pathType: ImplementationSpecific